// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // migrações usam a conexão direta (session pooler) — a pooled em modo
    // transação (DATABASE_URL, usada em runtime) não suporta DDL/prepared
    // statements de forma confiável
    url: process.env["DIRECT_URL"],
  },
});
